### PR TITLE
Client portals

### PR DESCRIPTION
**Pull request by telephant00**
@jtcreate @rosston 

Here's about as much as I could pull off by Monday morning. ;)

I spoke with MM about implementing Bourbon mixin library, and in the process of that I ended up migrating all the styles from LESS to Sass. I also reorganized the stylesheets structure according to atomic design principals and regression tested everything so I think we're good there. Please give a look-see and pass along any edits you might have.

### CODE REVIEW

**Comment by rosston** [comment]
@telephant00 Looks like you removed `less` from the Gemfile. `therubyracer` should be able to go too, right? I'm fighting with `bundle install` right now. Probably should've tried to install before this morning. :smile:

**Comment by telephant00** [comment]
Yes, I think you're right! I don't see that we need therubyracer other than for LESS.

**Comment by rosston** [comment]
Can you remove that from the Gemfile and Gemfile.lock in this branch? Getting `therubyracer` to install is the worst.

**Comment by telephant00** [comment]
Yep, one sec.

**Comment by rosston** [comment]
Ah, wait, hold on one sec. I think it might be used to uglify the JS.

**Comment by telephant00** [comment]
ok

**Comment by rosston** [comment]
Yeah, it is. Okay, so `therubyracer` stays. :(

**Comment by telephant00** [comment]
Boo. ;)

**Comment by rosston** [comment]
It's up at http://staging.envoyplatform.com/client-portal/ now. I think that's the only public-facing URL as a result of this, right?

A couple things I noticed (no idea if these are actually important, so absolutely feel free to ignore me):
* The person/contact images give a 404 (looks like the path references are a little mixed up).
* The Columbia brand logo gives a 404 when loading the page without the trailing slash (i.e., http://staging.envoyplatform.com/client-portal). There's probably not a way to solve that without an absolute path.

I have no idea what the next step is on any of this. I guess I'll probably leave it in @jtcreate's hands from here. Let me know if I need to do anything else!

**Comment by telephant00** [comment]
Created the Login page and styles. Installed Middleman-Gibberish, but it was throwing errors upon build. Ran out of time tonight to debug.

**Comment by telephant00** [comment]
Also! Created an awesome CSS timeline with associated data in the yaml file. Check it out!

**Comment by rosston** [comment]
@telephant00 I just put everything up through 8c728b0 on staging.envoyplatform.com. I left out everything after that due to Gibberish breaking the build.

**Comment by telephant00** [comment]
OK, this new commit has an updated Formspree code. Have @jtcreate try that. I have not validated it yet, which is what I believe the problem was with the last form. I validated it locally, but it needs to be done on production to be verified properly by Formspree.io. I think that's why we were getting a 403 error before.

**Comment by telephant00** [comment]
Shoot, I reset to the wrong branch, one sec.

**Pull request merged**
